- .eslintignore
- .eslintrc
- README.md
- config/constants.js
- config/environments.js
- config/index.js
- package.json
- src/routes/Home/modules/home.js
- src/utils/helpers.js
- tests/routes/Home/modules/home.spec.js
- yarn.lock
Adds ability to define `API_URL`, `API_VERSION` & `PAGE_SIZE` through environmental values (on production) and with fallback on constansts.js. Fixes #6.
> non-hardcoded global variables

- .env.example
- config/index.js
- server/controllers/authController.js
Add configurable `CLIENT_AUDIENCE`
> Configurable audience

- src/routes/ViewTOS/components/ViewTOS.js
- src/routes/ViewTOS/containers/ViewTOSContainer.js
- src/routes/ViewTOS/tosReducer.js
Clicking on 'Cancel editing' -button returns the original TOS
> Cancel editing returns original tos

- src/store/userReducer.js
Fixes CORS-error on production
> Set mode to `no-cors` on logout

- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/Record/reducer.js
> Allow nullable on Record

- package.json
- src/components/Tos/Action/CreateActionForm.js
- src/components/Tos/Phase/CreatePhaseForm.js
- src/components/Tos/Phase/Phase.js
- src/components/Tos/ViewTos/ViewTos.js
- src/decorators/key-stroke-support.js
To actually submit forms with `enter` & `esc`
> Add keyStrokeSupport-decorator

- src/utils/validators.js
> Fixed requiredIf validation

- src/components/Loader/Loader.scss
- src/components/Tos/Phase/Phase.scss
- src/components/Tos/ValidationBar/ValidationBar.js
> Fixed sticky header

- src/components/Tos/ValidationBar/ValidationBar.js
> Fix double vertical scrollbar

- src/main.js
- src/utils/api.js
> Dispatch logout when API responds with status 401

- src/components/Tos/AddElementInput/AddElementInput.js
- src/components/Tos/Attribute/Attribute.js
- src/components/Tos/DropdownInput/DropdownInput.js
- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/ViewTos/ViewTos.js
- src/store/uiReducer.js
- src/utils/validators.js
> Support for multi select and adding new values to select.

- src/components/Tos/ValidationBar/ValidationBar.js
- src/components/Tos/ValidationBar/ValidationBar.scss
- src/utils/validators.js
> Warn type validation errors. Filtering validation errors by type.

- .env.example
- config/index.js
* Add SERVER_HOST environment variable to define host name
Fixes #117
> Fix local environment CORS issues

- src/components/Tos/Action/Action.js
- src/components/Tos/Action/Action.scss
- src/components/Tos/Attribute/Attribute.scss
- src/components/Tos/Phase/Phase.js
- src/components/Tos/Phase/Phase.scss
> Only basic attributes shown in phase and action sticky headers.

- src/components/Tos/EditorForm/EditorForm.js
- src/utils/validators.js
> Validate required empty

- src/components/Tos/Attribute/Attribute.js
- src/components/Tos/DropdownInput/DropdownInput.js
> Fix select element not showing value that includes comma

- src/components/Banner/index.js
> Add target='_blank' to the info page link in the banner

- src/components/Tos/Header/ActionButtons.js
- src/components/Tos/Print/PrintView.js
- src/components/Tos/VersionSelector/VersionSelector.js
- src/components/Tos/VersionSelector/VersionSelector.scss
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/reducer.js
- src/routes.js
- src/utils/helpers.js
> Version selector and saved version mismatch notification

- src/components/Tos/Print/PrintView.js
> Fix bug in attributes sort

- src/components/Classification/Header/ClassificationButton.js
- src/components/Classification/Header/ClassificationHeader.js
- src/components/Classification/ViewClassification/ViewClassification.js
- src/components/Classification/ViewClassification/ViewClassification.scss
- src/components/Classification/ViewClassification/ViewClassificationContainer.js
- src/components/Classification/reducer.js
- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.js
- src/components/Navigation/Navigation.scss
- src/components/Navigation/NavigationContainer.js
- src/components/Navigation/reducer.js
- src/routes.js
- src/store/rootReducers.js
- src/utils/helpers.js
> Navigation uses classification api. Create new tos for classification.

- src/components/Navigation/Navigation.js
- src/components/Navigation/Navigation.scss
> Fix only partly visible navigation filter dropdown

- src/components/Navigation/Navigation.js
- src/components/Navigation/NavigationContainer.js
> Reset navigation tree when navigating to new URL

- src/components/Tos/CloneView/CloneView.js
> Fix clone function to use function id instead of classification id

- src/components/Navigation/NavigationContainer.js
> Reset navigation using key prop to tell when route changes

- src/components/Tos/Print/MetaDataTable.js
> Fix array values format in print view

- src/components/Tos/EditorForm/EditorForm.js
> Fix Add Record form submitting onblur/onchange

- src/components/Classification/ViewClassification/ViewClassification.js
> Add title for classification attributes table

- src/components/Navigation/Navigation.js
- src/static/humans.txt
Fixes #138
* Open navigation tree nodes if at least one status filter is selected
* Add my name to humans.txt
> Open navigation tree nodes if at least one status filter is selected

- src/components/Tos/Header/TosHeader.js
- src/components/Tos/ViewTos/ViewTos.js
> Add link to classification in TOS header

- src/components/InfinityMenu/infinityMenu.js
- src/components/InfinityMenu/searchInput.js
- src/components/Navigation/Navigation.js
> Remove onClick handler from InfinityMenu's SearchInput

- src/components/Navigation/Navigation.js
- src/components/Navigation/NavigationContainer.js
> Update navigation after login and user data

- src/components/InfinityMenu/infinityMenu.js
> Remove extranous prop

- src/components/IsAllowed/IsAllowed.js
- src/components/Login/Login.js
- src/components/Login/LoginContainer.js
- src/components/Login/reducer.js
- src/components/Navigation/Navigation.js
- src/components/Navigation/NavigationContainer.js
- src/containers/AppContainer.js
Fixes #175.
Prevents API calls race conditions when logging in.
> Retrieve user data from session in the root component

- src/components/Classification/Header/ClassificationHeader.js
- src/components/Classification/ViewClassification/ViewClassification.js
- src/components/Classification/ViewClassification/ViewClassification.scss
> Classification print view

- config/constants.js
- src/store/uiReducer.js
- src/utils/validators.js
- tests/validators/attributeRules.json
> Fetch allow_values_outside_choices validation rules from api

- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.js
> Updated navigation filter state field placeholder text

- src/components/ClassificationTree/ClassificationTree.js
- src/components/ClassificationTree/ClassificationTree.scss
- src/components/ClassificationTree/ClassificationTreeContainer.js
- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.scss
- src/routes.js
> Classification tree print view

- bin/compile.js
- config/environments.js
- config/webpack-compiler.js
- config/webpack.config.js
- package.json
- server/main.js
- src/components/Tos/Attribute/Attribute.js
- src/components/Tos/DropdownInput/DropdownInput.js
- src/components/Tos/ValidationBar/ValidationBar.js
- yarn.lock
Are these hooks welcome?
* Add precommit hook: lint
* Add prepush hook: lint & test
* Fix linter errors and warnings
> Enforce linting and tests

- src/components/InfinityMenu/infinityMenu.js
> Fixed state filter text

- src/components/Tos/Print/PrintView.js
> Fixed function state text on function print view

- src/components/Classification/Header/ClassificationHeader.js
- src/components/ClassificationTree/ClassificationTree.js
- src/components/ClassificationTree/ClassificationTree.scss
- src/components/Tos/Print/PrintClassification.js
- src/components/Tos/Print/PrintView.js
- src/components/Tos/Print/PrintView.scss
Classification added to tos print view. Print button removed from classification view. Improved copy and paste to Excel.
Fixes #190 
Fixes #194
> Classification added to tos print view

- src/utils/validators.js
> Validate is attribute allowed in type (function, phase, action, record)

- src/components/Info/content_fi.md
Updated info page fi "Tietoa palvelusta"
> Update content_fi.md 

- src/components/Tos/Action/Action.js
- src/components/Tos/Record/Record.js
- src/components/Tos/Record/reducer.js
Fixes #210 Record delete do not work correctly
> Fixed delete record

- src/components/Tos/Action/Action.scss
- src/components/Tos/Action/reducer.js
- src/components/Tos/AddElementInput/AddElementInput.js
- src/components/Tos/AddElementInput/AddElementInput.scss
- src/components/Tos/Attribute/Attribute.js
- src/components/Tos/Attribute/Attribute.scss
- src/components/Tos/Attribute/Attributes.js
- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/Phase/Phase.js
- src/components/Tos/Phase/Phase.scss
- src/components/Tos/Phase/reducer.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
- src/store/uiReducer.js
> InformationSystem field visibility

- src/components/Tos/Attribute/Attributes.js
> Default attributes visibility on view mode

- src/components/Tos/Action/Action.js
- src/components/Tos/Action/Action.scss
- src/components/Tos/AddElementInput/AddElementInput.js
- src/components/Tos/Attribute/Attribute.js
- src/components/Tos/Attribute/Attribute.scss
- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/Phase/Phase.js
- src/components/Tos/Phase/Phase.scss
> Creatable select component when adding new elements

- src/components/Tos/Action/Action.js
- src/components/Tos/DeleteView/DeleteView.js
- src/components/Tos/Phase/Phase.js
- src/components/Tos/Record/Record.js
Fixed delete view message text spaces and the name of the target when TypeSpecifier is empty
> Fixed delete view message

- src/components/Tos/ValidationBar/ValidationBar.js
> Renamed validation bar title

- LICENSE
Updated LICENCE content CC information
> #228-licence-cc

- .gitignore
- src/components/Tos/AddElementInput/AddElementInput.js
> Fix add phase add action information system bug

- config/constants.js
- src/components/Exporter/Exporter.js
- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.js
- src/components/Navigation/NavigationContainer.js
- src/components/Navigation/SearchFilter.js
- src/routes.js
- yarn.lock
`/search` exposes the filtered search functionality & export.
Fixes #241
> Add route for filtered search

- src/components/Tos/AddElementInput/AddElementInput.js
- src/components/Tos/AddElementInput/AddElementInput.scss
Fix labels & add some padding & align.
Fixes #247
> Fix form labels

- config/index.js
- src/components/Banner/index.js
> Git version number on banner

- config/constants.js
- src/components/Navigation/Navigation.js
> Added search filter by record attribute RetentionPeriod

- src/components/Navigation/Navigation.scss
- src/components/Tos/Action/Action.js
- src/components/Tos/Action/reducer.js
- src/components/Tos/Phase/Phase.js
- src/components/Tos/Phase/reducer.js
- src/components/Tos/Record/Record.js
- src/components/Tos/Record/reducer.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
- src/components/Tos/ViewTos/ViewTosContainer.js
- src/components/Tos/reducer.js
- src/layouts/CoreLayout/CoreLayout.js
- src/layouts/CoreLayout/CoreLayout.scss
- src/utils/helpers.js
> Collapsing and expanding all tos metadata, phases, actions and records

- package.json
- yarn.lock
Bump node-sass to @latest so it'll be compatible w/ node v.10
> Bump node-sass

- src/components/Tos/ViewTos/ViewTos.js
> Changed valid_from and valid_to date format D.M.YYYY

- src/components/Tos/reducer.js
> Show api error message when save TOS fails

- src/components/Tos/Print/PrintView.js
- src/components/Tos/ViewTos/ViewTos.js
> Validation bar is closed on TOS view unmount

- package.json
- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.js
- src/components/Navigation/Navigation.scss
- yarn.lock
> Search by any attribute or field value

- src/components/Tos/Action/Action.js
- src/components/Tos/Header/ActionButtons.js
- src/components/Tos/Header/TosHeader.js
- src/components/Tos/Record/Record.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
> Improved TOS expand and collapse buttons and adding/editing record

- src/components/Tos/Phase/Phase.scss
> Remove phase button was not always clickable

- src/components/Tos/Header/ActionButtons.js
> Raportti button disabled on edit mode

- package.json
- src/components/InfinityMenu/infinityMenu.js
- yarn.lock
> Update defiant.js to version 1.4.5 to fix problem with IE

- src/components/Tos/ValidationBar/ValidationBar.js
> Updated validation error section name and removed unnecessary title

- src/components/Tos/reducer.js
> Save draft action mutated selected tos

- src/components/Exporter/Exporter.js
- src/components/InfinityMenu/infinityMenu.js
- src/components/Navigation/Navigation.js
Export button set visible when there are search results.
Exports search results, not just those filtered by state or retention period.
Fixes #294
> Export listed search results

- src/components/Navigation/Navigation.js
> Updated navigation fail message

- src/components/InfinityMenu/infinityMenu.js
- src/components/Info/ViewInfo.js
- src/components/Info/ViewInfo.scss
- src/components/Navigation/Navigation.scss
- src/components/Tos/Action/Action.scss
- src/components/Tos/Attribute/Attribute.scss
- src/components/Tos/Phase/Phase.scss
- src/components/Tos/ViewTos/ViewTos.scss
> Navigation and info text side by side on front page

- src/components/Header/Header.js
- src/components/Header/Header.scss
- src/components/Info/ViewInfo.scss
- src/components/Login/Login.js
- src/components/Navigation/Navigation.scss
> Front page, navigation and header style fixes

- config/constants.js
- src/components/Tos/Header/ActionButtons.js
- src/components/Tos/Header/TosHeader.js
- src/components/Tos/ValidationBar/ValidationBar.js
- src/components/Tos/ValidationBar/ValidationBar.scss
- src/components/Tos/ValidationBarHeader/ValidationBarHeader.js
- src/components/Tos/ValidationBarHeader/ValidationBarHeader.scss
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
Validation bar header with close button and filters stick always visible even view is scrolled
Fixes #304
> Sticky validation bar header

- src/components/Classification/ViewClassification/ViewClassification.scss
- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/Header/ActionButtons.js
- src/components/Tos/Header/ClassificationHeader.js
- src/components/Tos/ValidationBarHeader/ValidationBarHeader.scss
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
- src/components/Tos/ViewTos/ViewTosContainer.js
- src/components/Tos/reducer.js
- src/routes.js
- view all TOS data shows also classification data and url is replaced to end with "/all"
- view basic data and hide all does not show tos version and metadata
- title updates and minor structure updates
Fixes #312
> View all / view basic / hide all actions

- src/components/Tos/EditorForm/EditorForm.js
- src/components/Tos/Header/ActionButtons.js
- src/components/Tos/Header/ClassificationHeader.js
- src/components/Tos/Header/TosHeader.js
- src/components/Tos/Version/VersionData.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTos.scss
- src/components/Tos/ViewTos/ViewTosContainer.js
- src/components/Tos/reducer.js
- src/routes.js
> Show all TOS data by default

- src/components/Info/content_fi.md
> About information update Update content_fi.md

- src/components/Tos/Version/VersionData.js
- src/components/Tos/ViewTos/ViewTos.js
> Clone view link moved next to TOS metadata buttons

- src/components/Login/reducer.js
- src/components/Tos/Print/PrintView.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTosContainer.js
- src/components/Tos/reducer.js
- src/utils/api.js
> Handle unauthorized api request, redirect to login

- src/components/Bulk/BulkCreateView/BulkCreateView.js
> Fixed bulk update package selected items validation check

- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/reducer.js
> Tos basic and classification data opened by default

- src/components/Navigation/Navigation.scss
> Fixed navigation dropdown styling

- src/utils/validators.js
> Fixed editor form not showing all fields

- src/components/FacetedSearch/reducer.js
> Fixed faceted search excel exporter to export all classifications

- src/components/FacetedSearch/reducer.js
> Faceted search: fixed attribute value hit count increased

- src/components/FacetedSearch/FacetedSearch.js
> Faceted search: attribute values in alphabetic order

- src/components/Header/Header.js
> Fixed faceted search link

- src/components/Classification/reducer.js
- src/components/FacetedSearch/reducer.js
- src/components/Navigation/NavigationContainer.js
- src/components/Tos/Print/PrintView.js
- src/components/Tos/ViewTos/ViewTos.js
- src/components/Tos/ViewTos/ViewTosContainer.js
- src/utils/helpers.js
- change UI to comply with recent API changes
Proposed fix to #412
> Fix broken classification references

- src/components/Classification/VersionSelector/VersionSelector.js
- src/components/Classification/VersionSelector/VersionSelector.scss
- src/components/Classification/ViewClassification/ViewClassification.js
- src/components/Classification/ViewClassification/ViewClassification.scss
- src/components/Tos/Header/ClassificationHeader.js
- src/components/Tos/Version/VersionData.js
- src/routes.js
> Make classification version selectable

- .github/workflows/ci.yaml
- sonar-project.properties
**[TIED-51](https://helsinkisolutionoffice.atlassian.net/browse/TIED-51)**
[TIED-51]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add SonarCloud scan to CI workflow

- src/components/InfinityMenu/InfinityMenu.jsx
Fixing bug where search filters are rendered on every input change.
**[TIED-80](https://helsinkisolutionoffice.atlassian.net/browse/TIED-80)**
[TIED-80]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TIED-80 bugfix search input focus

- pipelines/tiedonohjaus-ui-release.yml
- pipelines/tiedonohjaus-ui-review.yml
- pipelines/tiedonohjaus-ui-test.yml
**[TIED-138](https://helsinkisolutionoffice.atlassian.net/browse/TIED-138)**
[TIED-138]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: remove temporaly ref from pipelines

- pipelines/tiedonohjaus-ui-review.yml
set api url for review builds
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX)**
> build: review pipeline define api url

- .prod/nginx.conf
Related PR https://dev.azure.com/City-of-Helsinki/tiedonohjaus/_git/tiedonohjaus-pipelines/pullrequest/6795
Ref TIED-123
> fix: add Content-Type to nginx probe responses

- pipelines/tiedonohjaus-ui-dev.yml
- pipelines/tiedonohjaus-ui-review.yml
**[OH-28](https://helsinkisolutionoffice.atlassian.net/browse/OH-28)**
[OH-28]: https://helsinkisolutionoffice.atlassian.net/browse/OH-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: change pipeline name from test to dev OH-28

- pipelines/tiedonohjaus-ui-review.yml
Fixing small typo in UI review pipeline arguments
**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX)**
> fix: pipelines ui review, fix React app api url

- src/components/Header/Header.jsx
- src/components/Login/Login.jsx
- src/components/Login/LoginContainer.jsx
- src/components/Login/__tests__/Login.test.jsx
- src/components/Login/reducer.js
- src/components/LoginCallback/LoginCallback.jsx
- src/components/LoginCallback/LoginCallbackContainer.jsx
- src/containers/AppContainer.jsx
- src/routes.jsx
Bug fix: should set user data in Redux state correctly
**[TIED-129](https://helsinkisolutionoffice.atlassian.net/browse/TIED-129)**
Tested on local machine
[TIED-129]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fixing set user state on login TIED-129

- src/components/InfinityMenu/SearchFilter/__tests__/__snapshots__/SearchFilters.test.jsx.snap
- src/components/InfinityMenu/__tests__/__snapshots__/InfinityMenu.test.jsx.snap
- src/components/Tos/Attribute/Attribute.jsx
- src/components/Tos/EditorForm/__tests__/__snapshots__/EditorForm.test.jsx.snap
- yarn.lock
Fixes bug of metadata not visible
**[TIED-141](https://helsinkisolutionoffice.atlassian.net/browse/TIED-141)**
How to test instructions in Jira ticket
[PR test environment](https://tiedonohjaus-pr526-ui.dev.hel.ninja/)
[TIED-141]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 141 show attributes bug

- src/components/Tos/Phase/Phase.jsx
- src/components/Tos/Reorder/ReorderItem.jsx
- src/components/Tos/Reorder/reducer.js
Fix small bugs on reorder code. There was a different bug on each structure level (phase, action, record)
**[TIED-148](https://helsinkisolutionoffice.atlassian.net/browse/TIED-148)**
The Jira ticket has good step-by-step instructions and a video on how to reproduce these bugs.
[TIED-148]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: reorder bugs TIED-148

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/DropdownMenuWrapper.jsx
- src/components/Dropdown/__tests__/Dropdown.test.jsx
Fixing bug where clicking outside does not currently close the dropdown.
**[TIED-154](https://helsinkisolutionoffice.atlassian.net/browse/TIED-154)**
[TIED-154]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: dropdown fixing clicking outside TIED-154

- src/components/Tos/ValidationBar/ValidationBar.jsx
- src/components/Tos/ValidationBar/ValidationBar.scss
- src/components/Tos/ValidationBar/__tests__/ValidationBar.test.jsx
- src/components/Tos/ValidationBar/__tests__/__snapshots__/ValidationBar.test.jsx.snap
Fix validation bar not showing success icon
**[TIED-155](https://helsinkisolutionoffice.atlassian.net/browse/TIED-155)**
[TIED-155]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: validation bar fix no missing attributes icon TIED-155

- src/components/Tos/Phase/Phase.jsx
> fix: add null check to getTargetName hasType

- src/components/Tos/Action/Action.jsx
- src/components/Tos/Phase/Phase.jsx
- src/components/Tos/Reorder/ReorderItem.jsx
- src/components/Tos/Reorder/ReorderView.jsx
- src/views/Tos/ViewTos/ViewTos.jsx
https://helsinkisolutionoffice.atlassian.net/browse/TIED-170?focusedCommentId=128501
> fix: reorder items bug fix TIED-170

- README.md
- e2e/tests/pages/frontpage-spec.js
- e2e/tests/pages/searchpage-spec.js
- e2e/tests/utils.js
- package.json
- playwright.config.js
Add some more coverage to e2e playwright tests.
Fix wrong dev urls
Mention e2e tests in readme
**[TIED-199](https://helsinkisolutionoffice.atlassian.net/browse/TIED-199)**
[TIED-199]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: e2e update TIED-199

- src/components/Tos/Action/__tests__/Action.test.jsx
- src/components/Tos/CloneView/__tests__/cloneFromTemplate.test.js
- src/components/Tos/EditorForm/EditorForm.jsx
- src/components/Tos/ImportView/ImportView.jsx
- src/components/Tos/Phase/Phase.jsx
- src/components/Tos/Phase/__tests__/Phase.test.jsx
- src/components/Tos/Record/__tests__/Record.test.jsx
- src/components/Tos/Reorder/ReorderView.jsx
- src/store/reducers/__tests__/bulk.test.js
- src/store/reducers/__tests__/classification.test.js
- src/store/reducers/__tests__/tos.test.js
- src/store/reducers/bulk.js
- src/store/reducers/classification.js
- src/store/reducers/tos-toolkit/action.js
- src/store/reducers/tos-toolkit/cloneView.js
- src/store/reducers/tos-toolkit/main.js
- src/store/reducers/tos-toolkit/phase.js
- src/store/reducers/tos-toolkit/record.js
- src/views/Bulk/BulkListView.jsx
- src/views/Bulk/BulkView/BulkView.jsx
- src/views/Bulk/BulkView/__tests__/BulkView.test.jsx
- src/views/Bulk/__tests__/BulkListView.test.jsx
- src/views/Tos/Print/PrintView.jsx
- src/views/Tos/Print/__tests__/PrintView.test.jsx
- src/views/Tos/ViewTos/ViewTos.jsx
- src/views/Tos/ViewTos/__tests__/ViewTos.test.jsx
- src/views/ViewClassification/ViewClassification.jsx
- src/views/ViewClassification/__tests__/ViewClassification.test.jsx
- Administrator related thunks should pass API token always.
- Fixing adding / removing phases, actions and records on ViewTos page.
**[TIED-203](https://helsinkisolutionoffice.atlassian.net/browse/TIED-203)**
[TIED-203]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TIED-203 ViewTos page fixes

- .yarnrc
- src/store/reducers/__tests__/tos.test.js
- src/views/Tos/ViewTos/ViewTos.jsx
- src/views/Tos/ViewTos/__tests__/ViewTos.test.jsx
Should be able to add phases without specific phase type.
**[TIED-213](https://helsinkisolutionoffice.atlassian.net/browse/TIED-213)**
[TIED-213]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TIED-213 Add phases without type
